import type { Product } from "./types";

export const SITE = "https://multinicheai.com";
export const BRAND = "MULTINICHE AI";
export const COPYRIGHT_YEAR = 2026;
export const COPYRIGHT = `© ${COPYRIGHT_YEAR} ${BRAND}. All rights reserved.`;
export const SWARM_SKU = "AI-AB-070";
export const SWARM_REPO = "https://github.com/duprejesse3-ops/swarm";

export const PRODUCTS: Product[] = [
  {
    sku: "AI-AB-070",
    name: "SWARM Intent Autopilot",
    price: 79,
    format: "Automation",
    role: "Store & Site Owners",
    job: "Hijack demand that already exists and evolve proof-first ads on autopilot",
    proof: "Autopilot maps a pain-utterance to a SKU, spawns eight organisms, evolves winners — no click",
    pain: "A catalog of instruments and nobody intercepts the sentences people already type.",
    queries: [
      "automate ads for ai tools site",
      "intent hijack ads not google tax",
      "autopilot ads for digital products",
    ],
    utterances: [
      "I have a catalog and no traffic",
      "Buying Google ads for AI tools is a tax",
      "Need ads that intercept the job people already typed",
    ],
    landing: "/product/AI-AB-070",
  },
  {
    sku: "AI-AB-002",
    name: "Inbox Zero Automation",
    price: 29,
    format: "Automation",
    role: "Sales & CS",
    job: "Zero an inbox without losing the messages that need a human",
    proof: "2,400-email dump sorted, drafted, and flagged in 11 minutes",
    pain: "Inbox is a second job. ChatGPT drafts one reply. The pile is still there.",
    queries: [
      "inbox zero automation",
      "ai email sorter that drafts replies",
      "zapier gmail auto draft",
    ],
    utterances: [
      "I am drowning in Gmail and ChatGPT is not helping",
      "Need something that sorts AND drafts, not another summarizer",
      "Inbox zero without living in my email",
    ],
    landing: "/proof",
  },
  {
    sku: "AI-AG-003",
    name: "Meeting Notes Agent",
    price: 15,
    format: "Agent",
    role: "Founders & Ops",
    job: "Turn a transcript into decisions, owners, and deadlines",
    proof: "47-minute standup → 9 decisions, 6 owners, 4 dates — no summary fluff",
    pain: "Notes that recap what was said instead of what was decided.",
    queries: [
      "ai meeting notes with action items",
      "transcript to owners and deadlines",
      "meeting notes agent not summarizer",
    ],
    utterances: [
      "I need action items from meetings, not a recap",
      "Who owns what from yesterday's call",
      "Meeting notes that extract decisions",
    ],
    landing: "/agent",
  },
  {
    sku: "AI-PP-001",
    name: "Deep Work Prompt Pack",
    price: 19,
    format: "Prompt Pack",
    role: "Founders & Ops",
    job: "Protect focus blocks and close the day clean",
    proof: "Priority stack + 90-minute block + end-of-day reset in one pack",
    pain: "Todo lists that grow. No operating rhythm.",
    queries: [
      "deep work prompts chatgpt",
      "daily prioritization prompt pack",
      "end of day reset ai",
    ],
    utterances: [
      "I keep starting the day in other people's priorities",
      "Need a shutdown ritual that actually sticks",
      "Deep work system for a solo founder",
    ],
    landing: "/product/AI-PP-001",
  },
  {
    sku: "AI-AB-005",
    name: "Content Calendar Autopilot",
    price: 24,
    format: "Automation",
    role: "Marketers",
    job: "Draft posts from notes and queue them by channel",
    proof: "One notes dump → 12 queued posts across 3 channels",
    pain: "A Notion calendar that is empty by Wednesday.",
    queries: [
      "ai content calendar automation",
      "draft social posts from notes",
      "queue linkedin twitter from one doc",
    ],
    utterances: [
      "I have notes but no posts go out",
      "Need a content engine that queues itself",
      "Tired of rewriting the same idea for every channel",
    ],
    landing: "/product/AI-AB-005",
  },
  {
    sku: "AI-PP-025",
    name: "Viral Hook Prompt Pack",
    price: 23,
    format: "Prompt Pack",
    role: "Marketers",
    job: "Write openings that stop the scroll on each platform",
    proof: "Platform-tuned hooks — not one line pasted everywhere",
    pain: "Good posts dying on line one.",
    queries: [
      "viral hook prompts",
      "scroll stopping opening lines",
      "linkedin hook formula ai",
    ],
    utterances: [
      "My posts die in the first line",
      "Need hooks that match the platform rhythm",
      "Tired of 'are you struggling with' openers",
    ],
    landing: "/product/AI-PP-025",
  },
  {
    sku: "AI-PP-014",
    name: "Landing Page Copy Prompts",
    price: 18,
    format: "Prompt Pack",
    role: "Marketers",
    job: "Headline, hero, and CTA variants for conversion tests",
    proof: "8 headline / hero / CTA sets ready to A/B, not one pretty draft",
    pain: "One hero line you are too close to judge.",
    queries: [
      "landing page copy prompts",
      "headline variants for ab test",
      "hero cta prompt pack",
    ],
    utterances: [
      "I need headline variants not another rewrite",
      "Landing page copy that is testable",
      "Hero section sounds like every other SaaS",
    ],
    landing: "/product/AI-PP-014",
  },
  {
    sku: "AI-AG-008",
    name: "Daily Standup Bot",
    price: 18,
    format: "Agent",
    role: "Developers",
    job: "Collect async updates and post a one-line team digest",
    proof: "Async standups → one digest, no 15-minute meeting",
    pain: "Standup that exists so standup can exist.",
    queries: [
      "async standup bot",
      "slack daily digest agent",
      "replace standup with ai digest",
    ],
    utterances: [
      "Standup is eating the morning",
      "Need async updates that someone actually reads",
      "Replace the 15 minute meeting",
    ],
    landing: "/agent",
  },
  {
    sku: "AI-AB-013",
    name: "Code Review Digest",
    price: 26,
    format: "Automation",
    role: "Developers",
    job: "Summarize open PRs into a daily digest with risk flags",
    proof: "Open PRs → risk-flagged digest before you open GitHub",
    pain: "PR tab as a second inbox.",
    queries: [
      "pr digest automation",
      "daily code review summary",
      "flag risky pull requests",
    ],
    utterances: [
      "I have 14 open PRs and no idea which is dangerous",
      "Need a morning digest of code review",
      "GitHub notifications are unusable",
    ],
    landing: "/product/AI-AB-013",
  },
  {
    sku: "AI-PP-011",
    name: "Writing Style Prompt Kit",
    price: 16,
    format: "Prompt Pack",
    role: "Writers",
    job: "Lock tone so drafts sound like you",
    proof: "Voice lock you can hand to any model — ChatGPT, Claude, Gemini",
    pain: "Every draft sounds like a template.",
    queries: [
      "writing style prompt kit",
      "make chatgpt sound like me",
      "brand voice system prompt",
    ],
    utterances: [
      "ChatGPT does not sound like me",
      "Need a voice lock I can reuse",
      "Drafts come out corporate even when I am not",
    ],
    landing: "/product/AI-PP-011",
  },
  {
    sku: "AI-PP-029",
    name: "Voice & Tone Cloner",
    price: 19,
    format: "Prompt Pack",
    role: "Writers",
    job: "Capture any brand voice into a reusable system prompt",
    proof: "Paste 3 samples → a system prompt you can hand to any model",
    pain: "Brand guidelines nobody's model follows.",
    queries: [
      "clone writing voice prompt",
      "brand tone system prompt",
      "voice cloner for chatgpt",
    ],
    utterances: [
      "I want to clone a newsletter voice",
      "Brand tone dies the moment we open ChatGPT",
      "Need a reusable voice prompt from samples",
    ],
    landing: "/product/AI-PP-029",
  },
  {
    sku: "AI-PP-006",
    name: "Research Assistant Prompts",
    price: 22,
    format: "Prompt Pack",
    role: "Students & Researchers",
    job: "Literature scans and source comparison without mush",
    proof: "Structured scans that keep sources attached to claims",
    pain: "A 2,000-word 'overview' with no citations you can trust.",
    queries: [
      "literature review prompts",
      "ai research assistant with sources",
      "compare papers prompt pack",
    ],
    utterances: [
      "Need a literature scan that keeps the sources",
      "ChatGPT mashed three papers into mush",
      "Research prompts that compare instead of summarize",
    ],
    landing: "/product/AI-PP-006",
  },
  {
    sku: "AI-AB-010",
    name: "Personal CRM Automation",
    price: 25,
    format: "Automation",
    role: "Sales & CS",
    job: "Follow up before a relationship goes cold",
    proof: "Nudges you before the thread dies — not after",
    pain: "A CRM you never open, relationships you lose.",
    queries: [
      "personal crm follow up automation",
      "relationship reminder not salesforce",
      "follow up before they go cold",
    ],
    utterances: [
      "I lose people because I forget to follow up",
      "Need a lightweight CRM that nags me",
      "Relationships going cold in my inbox",
    ],
    landing: "/product/AI-AB-010",
  },
  {
    sku: "AI-TP-007",
    name: "Client Onboarding Kit",
    price: 34,
    format: "Template",
    role: "Sales & CS",
    job: "Intake, welcome sequence, and kickoff in one kit",
    proof: "Intake + welcome + kickoff — the first week stops being chaos",
    pain: "Every new client reinvented from Slack messages.",
    queries: [
      "client onboarding kit notion",
      "welcome sequence template",
      "kickoff checklist for agencies",
    ],
    utterances: [
      "Every new client is chaos for a week",
      "Need onboarding that is not a google doc graveyard",
      "Intake form plus kickoff in one kit",
    ],
    landing: "/product/AI-TP-007",
  },
  {
    sku: "AI-AG-012",
    name: "Financial Categorizer Agent",
    price: 27,
    format: "Agent",
    role: "Founders & Ops",
    job: "Read bank exports and sort spend into your categories",
    proof: "CSV in → categories you defined, not a bank's guess",
    pain: "Sunday night with a CSV and a headache.",
    queries: [
      "categorize bank csv ai",
      "expense categorizer agent",
      "sort spend into my categories",
    ],
    utterances: [
      "Bank categories are useless",
      "Need my CSV sorted into MY buckets",
      "Expense review is eating Sunday",
    ],
    landing: "/agent",
  },
  {
    sku: "AI-AB-060",
    name: "Cashflow Forecast Automation",
    price: 33,
    format: "Automation",
    role: "Finance & Investing",
    job: "Project 13-week cashflow from invoices and bills",
    proof: "13-week cash view so the crunch is visible before it hits",
    pain: "Finding out you are short the week payroll lands.",
    queries: [
      "13 week cashflow forecast",
      "invoice bill cash projection",
      "see cash crunch before payroll",
    ],
    utterances: [
      "I find out we are short the week payroll hits",
      "Need a 13-week cash view",
      "Invoices and bills into one forecast",
    ],
    landing: "/product/AI-AB-060",
  },
  {
    sku: "AI-AG-057",
    name: "Personal CFO Agent",
    price: 39,
    format: "Agent",
    role: "Finance & Investing",
    job: "Review spending, spot leaks, give three moves to hit the goal",
    proof: "Three moves toward the savings goal — not a lecture",
    pain: "Budget apps that shame you and do not tell you what to cut.",
    queries: [
      "personal cfo ai agent",
      "spending leaks three moves",
      "savings goal agent",
    ],
    utterances: [
      "I know I overspend I need the three cuts",
      "Budget apps lecture me",
      "Want a CFO not a pie chart",
    ],
    landing: "/agent",
  },
  {
    sku: "AI-AG-039",
    name: "On-Call Triage Agent",
    price: 45,
    format: "Agent",
    role: "Engineers",
    job: "Read the alert, pull the runbook, propose the first three checks",
    proof: "First three checks ready before you finish logging in",
    pain: "3am, twelve tabs, no first move.",
    queries: [
      "on call triage agent",
      "alert to runbook first checks",
      "pagerduty ai first three steps",
    ],
    utterances: [
      "3am and I do not know the first check",
      "Need the runbook pulled with the alert",
      "On-call is twelve tabs of archaeology",
    ],
    landing: "/agent",
  },
  {
    sku: "AI-AB-037",
    name: "Incident Postmortem Automation",
    price: 34,
    format: "Automation",
    role: "Engineers",
    job: "Turn an incident timeline into a blameless postmortem with owners",
    proof: "Timeline in → blameless draft with action items already assigned",
    pain: "Postmortems that never get written.",
    queries: [
      "incident postmortem automation",
      "blameless postmortem from timeline",
      "action items from incident",
    ],
    utterances: [
      "We never write the postmortem",
      "Need a blameless draft from the timeline",
      "Action items from incidents get lost",
    ],
    landing: "/product/AI-AB-037",
  },
  {
    sku: "AI-AG-033",
    name: "Threat Modeling Agent",
    price: 41,
    format: "Agent",
    role: "Architects",
    job: "Walk a design and surface attack paths you missed",
    proof: "Attack paths, trust boundaries, mitigations — before you ship",
    pain: "Threat models that happen after the breach report.",
    queries: [
      "threat modeling agent",
      "attack paths from design doc",
      "ai stride threat model",
    ],
    utterances: [
      "We skip threat modeling until something breaks",
      "Need attack paths from a design doc",
      "Principal-level questions before the review",
    ],
    landing: "/agent",
  },
  {
    sku: "AI-AG-065",
    name: "Site Audit Agent",
    price: 79,
    format: "Agent",
    role: "Store & Site Owners",
    job: "A maintenance agent that watches your site on your hardware",
    proof: "Unzip, ./install.sh — site-audit command on your machine",
    pain: "Finding out the site is down from a customer.",
    queries: [
      "self hosted site audit agent",
      "website watchdog on my hardware",
      "install.sh site maintenance agent",
    ],
    utterances: [
      "I find out the site is down from a customer",
      "Want a watchdog that runs on my machine",
      "Need a site audit I actually own",
    ],
    landing: "/product/AI-AG-065",
  },
  {
    sku: "AI-CN-001",
    name: "MultiConnect: Zapier/Webhook Bridge",
    price: 29,
    format: "Connector",
    role: "Developers",
    job: "Wire an agent to any app in minutes — no code, both directions",
    proof: "Outbound + inbound webhooks, visual payload mapping, live test console",
    pain: "The agent works. It just can't talk to the fifteen other tools you use.",
    queries: [
      "connect ai agent to zapier",
      "webhook bridge no code",
      "agent to app integration",
    ],
    utterances: [
      "My agent can't reach Zapier without a dev",
      "Need a webhook in and out, no code",
      "Wiring every integration by hand is the bottleneck",
    ],
    landing: "/product/AI-CN-001",
  },
  {
    sku: "AI-CN-002",
    name: "MultiConnect: Shopify",
    price: 59,
    format: "Connector",
    role: "Store & Site Owners",
    job: "Give the agent live Shopify data — inventory, orders, triggers",
    proof: "Product/inventory sync, order visibility, webhook triggers, read-only or read/write",
    pain: "The agent is guessing at stock levels instead of checking the store.",
    queries: [
      "shopify ai agent connector",
      "sync shopify inventory to agent",
      "shopify webhook triggers ai",
    ],
    utterances: [
      "Agent needs to see real Shopify inventory",
      "Want order triggers to kick off tasks",
      "Tired of the agent guessing what's in stock",
    ],
    landing: "/product/AI-CN-002",
  },
  {
    sku: "AI-CN-003",
    name: "MultiConnect: Sheets/Airtable",
    price: 35,
    format: "Connector",
    role: "Office & Admin",
    job: "Turn a spreadsheet into the agent's database — two-way, no code",
    proof: "Row read/write, column mapping, two-way sync, Sheets + Airtable in one app",
    pain: "The team's actual source of truth is a spreadsheet the agent can't touch.",
    queries: [
      "connect ai agent to google sheets",
      "airtable agent sync",
      "spreadsheet as agent database",
    ],
    utterances: [
      "Everything lives in a spreadsheet, not a database",
      "Need two-way sync between agent and Sheets",
      "Airtable is where the real data is",
    ],
    landing: "/product/AI-CN-003",
  },
  {
    sku: "AI-CN-004",
    name: "MultiConnect: Email/CRM",
    price: 79,
    format: "Connector",
    role: "Sales & CS",
    job: "Let the agent draft, send, and follow up on leads — with approval control",
    proof: "Read/draft/send, CRM contact sync, inbound-triggered tasks, approval queue + send limits",
    pain: "Nobody will let an agent near the inbox without a human checking every send.",
    queries: [
      "ai agent email approval queue",
      "agent crm follow up leads",
      "safe ai email sending",
    ],
    utterances: [
      "Need approval before the agent sends anything",
      "Agent should follow up on leads automatically",
      "Won't let an agent email customers unsupervised",
    ],
    landing: "/product/AI-CN-004",
  },
  {
    sku: "AI-CN-005",
    name: "MultiConnect: Slack/Discord",
    price: 25,
    format: "Connector",
    role: "Office & Admin",
    job: "Bring the agent into the channels the team already uses",
    proof: "Channel updates/alerts, slash-command support, per-event channel routing, Slack + Discord",
    pain: "Alerts live in a dashboard nobody opens instead of the channel everyone's already in.",
    queries: [
      "ai agent slack integration",
      "agent discord alerts",
      "slash command ai agent",
    ],
    utterances: [
      "Want agent updates in Slack, not another dashboard",
      "Need alerts routed to the right channel automatically",
      "Team lives in Discord, agent should too",
    ],
    landing: "/product/AI-CN-005",
  },
  {
    sku: "AI-CN-006",
    name: "MultiWitness",
    price: 69,
    format: "Connector",
    role: "Founders & Ops",
    job: "A tamper-evident log of what the agent actually did",
    proof: "Zero deps, SHA-256 hash chain, offline CLI verify",
    pain: "\"Trust me, the agent did what it said\" isn't proof anyone can check.",
    queries: [
      "tamper evident ai agent log",
      "hash chain audit log ai",
      "prove what my agent did",
    ],
    utterances: [
      "Need proof of what the agent actually did, not just logs",
      "Client wants an audit trail I can hand over",
      "Can't just say trust me about an autonomous agent",
    ],
    landing: "/product/AI-CN-006",
  },
  {
    sku: "AI-CN-007",
    name: "MultiGuard",
    price: 59,
    format: "Connector",
    role: "Founders & Ops",
    job: "One dashboard, one button, to lock down every connector at once",
    proof: "Works with any connector not just ours, offline-safe by design, zero deps",
    pain: "An incident means five separate dashboards and five separate read-only switches.",
    queries: [
      "kill switch for ai agent connectors",
      "one dashboard multiple integrations",
      "lock down ai agent access fast",
    ],
    utterances: [
      "Need one kill switch for every connector during an incident",
      "Checking five dashboards to find what's exposed is too slow",
      "Want everything read-only with one button",
    ],
    landing: "/product/AI-CN-007",
  },
  {
    sku: "AI-CN-008",
    name: "MultiVault",
    price: 79,
    format: "Connector",
    role: "Founders & Ops",
    job: "Local encrypted snapshot of a folder — searchable, yours",
    proof: "Runs on your machine. No account. No cloud copy of the corpus.",
    pain: "Putting the company's files into someone else's chat box.",
    queries: [
      "local encrypted knowledge vault",
      "private ai over my folder",
      "no cloud document search",
    ],
    utterances: [
      "I will not upload the company folder to a chatbot",
      "Need local search over my files",
      "Private vault, no account",
    ],
    landing: "/product/AI-CN-008",
  },
  {
    sku: "AI-HOST-001",
    name: "Meridian Host",
    price: 99,
    format: "Host",
    role: "Store & Site Owners",
    job: "Run the store on hardware you own",
    proof: "Perpetual license, no rent, site on your machine",
    pain: "A store that dies if a SaaS bill lapses.",
    queries: [
      "self host storefront",
      "run my shop on my hardware",
      "no subscription store host",
    ],
    utterances: [
      "I do not want my store on a rented platform",
      "Need to run the shop on my own hardware",
      "Tired of subscription hostages",
    ],
    landing: "/product/AI-HOST-001",
  },
  {
    sku: "AI-AG-030",
    name: "Customer Churn Sentinel",
    price: 43,
    format: "Agent",
    role: "Founders & Ops",
    job: "Flag at-risk accounts while there is still time",
    proof: "Usage + support signals → at-risk list before they cancel",
    pain: "Churn you notice in the cancellation email.",
    queries: [
      "churn prediction agent",
      "at risk accounts from usage",
      "save customers before they cancel",
    ],
    utterances: [
      "We notice churn in the cancellation email",
      "Need at-risk accounts while we can still save them",
      "Usage dropped and nobody saw it",
    ],
    landing: "/agent",
  },
  {
    sku: "AI-PP-050",
    name: "Professional Email Prompt Pack",
    price: 16,
    format: "Prompt Pack",
    role: "Office & Admin",
    job: "Say the hard thing well — declines, follow-ups, status",
    proof: "Warm, short, gets read — not a three-paragraph hedge",
    pain: "Staring at a blank reply for twenty minutes.",
    queries: [
      "professional email prompts",
      "how to decline politely prompt",
      "follow up email that gets read",
    ],
    utterances: [
      "I stare at hard emails for twenty minutes",
      "Need declines that stay warm",
      "Follow-ups that actually get a reply",
    ],
    landing: "/product/AI-PP-050",
  },
  {
    sku: "AI-HOST-002",
    name: "Meridian Gate",
    price: 59,
    format: "Host",
    role: "Store & Site Owners",
    job: "Sit in front of every outbound AI call and block what shouldn't leave — customer data, Stripe keys, defaults to no.",
    proof: "Default is no. A receipt for what left.",
    pain: "AI tools quietly sending customer data and keys to someone else's server.",
    queries: [
      "outbound AI proxy self hosted",
      "block AI data leaving my server",
      "AI privacy proxy small business",
    ],
    utterances: [
      "No idea what my AI stack is actually sending out",
      "Want a receipt for what an AI call actually sent",
    ],
    landing: "/product/AI-HOST-002",
  },
  {
    sku: "AI-TP-004",
    name: "Weekly Planning Template",
    price: 12,
    format: "Template",
    role: "Students & Researchers",
    job: "Give you one weekly rhythm — plan Monday, review Friday — instead of a blank page every week.",
    proof: "Duplicate-and-go setup.",
    pain: "Every week starts from a blank page again.",
    queries: [
      "weekly planning notion template",
      "plan monday review friday template",
      "simple weekly planner students",
    ],
    utterances: [
      "Every Sunday I redesign my planner instead of using it",
      "Need a weekly rhythm that actually sticks",
    ],
    landing: "/product/AI-TP-004",
  },
  {
    sku: "AI-AG-067",
    name: "MultiBøT",
    price: 49,
    format: "Agent",
    role: "Developers",
    job: "Plan vehicle routes with real libraries and force a critic pass before any alternative ships.",
    proof: "The critic refuses to ship if the alternatives are just heuristic wobble.",
    pain: "Route-planning bots that give three near-identical heuristics dressed up as options.",
    queries: [
      "vehicle routing python agent",
      "route optimization tool real alternatives",
      "OR-Tools routing desktop app",
    ],
    utterances: [
      "Every routing tool gives me the same answer three times",
      "Want real alternatives, not three copies of one heuristic",
    ],
    landing: "/product/AI-AG-067",
  },
  {
    sku: "AI-TP-009",
    name: "OKR Tracker Template",
    price: 14,
    format: "Template",
    role: "Founders & Ops",
    job: "Set, track, and review OKRs in one sheet, no separate tool to maintain.",
    proof: "Google Sheets, no add-ons.",
    pain: "OKRs written once in January and never opened again.",
    queries: [
      "OKR tracker google sheets",
      "simple OKR template founders",
      "quarterly OKR review template",
    ],
    utterances: [
      "We wrote OKRs in January and never looked at them again",
      "Need OKRs that live somewhere we'll actually check",
    ],
    landing: "/product/AI-TP-009",
  },
  {
    sku: "AI-AG-026",
    name: "Personal Research Analyst",
    price: 29,
    format: "Agent",
    role: "Students & Researchers",
    job: "Track a topic on a schedule and brief you weekly with real sources, not guesses.",
    proof: "Scheduled runs + citation checks.",
    pain: "Falling behind on a research topic because no one's tracking it for you.",
    queries: [
      "standing research agent weekly brief",
      "automated literature tracking tool",
      "AI research assistant with citations",
    ],
    utterances: [
      "I keep meaning to track this topic and never do",
      "Want a weekly brief with real sources, not a guess",
    ],
    landing: "/product/AI-AG-026",
  },
  {
    sku: "AI-TP-027",
    name: "Investor Update Template",
    price: 15,
    format: "Template",
    role: "Founders & Ops",
    job: "Send a monthly investor update that keeps metrics honest and the ask impossible to miss.",
    proof: "Metrics block + clear ask section.",
    pain: "Investor updates that bury the ask or skip the bad numbers.",
    queries: [
      "monthly investor update template",
      "founder investor update format",
      "notion investor update email template",
    ],
    utterances: [
      "My investor updates always bury the actual ask",
      "Need a monthly update format that keeps me honest on metrics",
    ],
    landing: "/product/AI-TP-027",
  },
  {
    sku: "AI-AB-028",
    name: "Release Notes Bot",
    price: 27,
    format: "Automation",
    role: "Developers",
    job: "Draft customer release notes and an internal Slack summary from your actual merged PRs the moment you publish a release.",
    proof: "Commits CHANGELOG.md, sets the release body — a real workflow, not a blueprint you wire yourself.",
    pain: "Release notes that either never get written, or get written from memory, wrong.",
    queries: [
      "automate release notes from github",
      "generate changelog from merged PRs",
      "github actions release notes bot",
    ],
    utterances: [
      "Writing release notes from memory again and getting it wrong",
      "Need changelog generation that isn't a manual chore every release",
    ],
    landing: "/product/AI-AB-028",
  },
  {
    sku: "AI-AG-115",
    name: "MultiSignal",
    price: 46,
    format: "Agent",
    role: "Founders & Ops",
    job: "Check whether a number that moved in your business actually connects to anything happening outside it.",
    proof: "NO LINK is a valid run — never dressed up as proof, only plausibility.",
    pain: "Guessing why a metric moved instead of actually checking.",
    queries: [
      "explain metric spike external causes",
      "correlate business metric to news",
      "why did my numbers move this week",
    ],
    utterances: [
      "No idea why this number moved and I'm just guessing",
      "Tired of forcing a story onto a metric that has no real cause",
    ],
    landing: "/product/AI-AG-115",
  },
  {
    sku: "AI-AG-112",
    name: "MultiCascade",
    price: 42,
    format: "Agent",
    role: "Founders & Ops",
    job: "Run an idea through architect, builder, and critic passes — one model, honest visible steps, not a dashboard of fake teammates.",
    proof: "Critic cannot rubber-stamp — has to name a real flaw or say plainly why it found none.",
    pain: "Multi-agent tools that just simulate a team without any real disagreement.",
    queries: [
      "multi agent critic review workflow",
      "structured idea review architect builder critic",
      "AI agent that finds real flaws",
    ],
    utterances: [
      "Every multi-agent demo I've tried just agrees with itself",
      "Want a critic pass that can't just rubber-stamp the idea",
    ],
    landing: "/product/AI-AG-112",
  },
  {
    sku: "AI-AG-113",
    name: "MultiAugment",
    price: 39,
    format: "Agent",
    role: "Office & Admin",
    job: "Show the real tradeoffs and name whose call it is, instead of handing you a confident verdict.",
    proof: "Every answer ends with WHO DECIDES — never executes anything on your behalf.",
    pain: "AI tools that act like they made the decision instead of you.",
    queries: [
      "AI decision support not verdict",
      "AI tool that shows tradeoffs not answers",
      "decision framework AI assistant",
    ],
    utterances: [
      "Tired of AI just handing me a verdict like it's my boss",
      "Want the tradeoffs shown, not a fake-confident answer",
    ],
    landing: "/product/AI-AG-113",
  },
  {
    sku: "AI-TP-031",
    name: "Architecture Decision Record Kit",
    price: 19,
    format: "Template",
    role: "Architects",
    job: "Capture the decision, the rejected options, and why — so the next architect inherits reasoning, not folklore.",
    proof: "ADR + RFC + trade-off matrix.",
    pain: "Architecture decisions that live in one person's head until they leave.",
    queries: [
      "architecture decision record template",
      "ADR template notion",
      "RFC trade-off matrix template",
    ],
    utterances: [
      "Nobody remembers why we made this architecture call",
      "Need ADRs that actually capture what we rejected and why",
    ],
    landing: "/product/AI-TP-031",
  },
  {
    sku: "AI-PP-032",
    name: "System Design Prompt Pack",
    price: 24,
    format: "Prompt Pack",
    role: "Architects",
    job: "Pressure-test a design across scale, failure modes, and cost before you commit a line of it.",
    proof: "C4 diagrams + capacity math.",
    pain: "Finding out a design doesn't scale after it's already built.",
    queries: [
      "system design prompt pack",
      "pressure test architecture before building",
      "capacity planning prompts AI",
    ],
    utterances: [
      "We found the scaling problem after we'd already built it",
      "Want to pressure-test this design before committing to it",
    ],
    landing: "/product/AI-PP-032",
  },
  {
    sku: "AI-AB-034",
    name: "Architecture Diagram Sync",
    price: 33,
    format: "Automation",
    role: "Architects",
    job: "Regenerate a real architecture diagram from your codebase's actual structure on every push to main.",
    proof: "Commits only when it genuinely changed — grounded in a real scan, nothing invented.",
    pain: "Architecture diagrams that stopped matching the code a year ago.",
    queries: [
      "auto generate architecture diagram from code",
      "mermaid diagram from codebase github action",
      "keep architecture docs in sync",
    ],
    utterances: [
      "Our architecture diagram hasn't matched reality in a year",
      "Need the diagram to update itself instead of someone remembering to",
    ],
    landing: "/product/AI-AB-034",
  },
  {
    sku: "AI-TP-035",
    name: "Tech Radar Template",
    price: 16,
    format: "Template",
    role: "Architects",
    job: "Track what your org should adopt, trial, or retire, with the reasoning attached to each ring.",
    proof: "Adopt / Trial / Assess / Hold.",
    pain: "Tech choices made by whoever shouted loudest in Slack.",
    queries: [
      "tech radar template notion",
      "adopt trial assess hold template",
      "technology radar for engineering teams",
    ],
    utterances: [
      "Our tech choices get made by whoever's loudest in Slack",
      "Want a tech radar with the reasoning attached, not just a list",
    ],
    landing: "/product/AI-TP-035",
  },
  {
    sku: "AI-AG-036",
    name: "RFC Review Agent",
    price: 37,
    format: "Agent",
    role: "Architects",
    job: "Read a design doc like a principal engineer would and return sharp, specific questions before the meeting.",
    proof: "Scored against a design rubric.",
    pain: "RFC reviews that are just a skim and a thumbs up.",
    queries: [
      "AI RFC review tool",
      "design doc review agent",
      "automated architecture review before meeting",
    ],
    utterances: [
      "Half the RFC reviews I get are just a skim and a thumbs up",
      "Want sharp questions on this design before the meeting, not after",
    ],
    landing: "/product/AI-AG-036",
  },
  {
    sku: "AI-PP-038",
    name: "Infrastructure-as-Code Prompt Pack",
    price: 22,
    format: "Prompt Pack",
    role: "Engineers",
    job: "Generate, review, and refactor Terraform and Kubernetes manifests without the copy-paste drift.",
    proof: "Terraform + K8s + Helm.",
    pain: "Infra manifests that drift from what's actually running.",
    queries: [
      "terraform prompt pack",
      "kubernetes manifest review prompts",
      "IaC refactor prompts AI",
    ],
    utterances: [
      "Our terraform has drifted so far from what's actually deployed",
      "Copy-pasting K8s manifests and hoping I didn't break anything",
    ],
    landing: "/product/AI-PP-038",
  },
  {
    sku: "AI-AB-040",
    name: "Data Pipeline Monitor",
    price: 36,
    format: "Automation",
    role: "Engineers",
    job: "Catch silent pipeline failures and schema drift, then explain what broke in plain language.",
    proof: "dbt + Airflow + Great Expectations.",
    pain: "Pipelines that fail silently until someone notices the dashboard is wrong.",
    queries: [
      "detect silent data pipeline failure",
      "schema drift monitoring dbt",
      "airflow pipeline monitoring alerts",
    ],
    utterances: [
      "The pipeline failed silently for two weeks before anyone noticed",
      "Need schema drift caught before it breaks the dashboard downstream",
    ],
    landing: "/product/AI-AB-040",
  },
  {
    sku: "AI-TP-041",
    name: "Runbook Template Library",
    price: 18,
    format: "Template",
    role: "Engineers",
    job: "Give your team runbooks they can actually follow at 3am — deploys, rollbacks, recovery.",
    proof: "Deploy / rollback / restore plays.",
    pain: "3am incidents with no runbook, just tribal knowledge.",
    queries: [
      "incident runbook template",
      "deploy rollback runbook notion",
      "on call runbook library",
    ],
    utterances: [
      "3am and there's no runbook, just whoever remembers how this works",
      "Need rollback steps written down before the next incident, not during it",
    ],
    landing: "/product/AI-TP-041",
  },
  {
    sku: "AI-PP-042",
    name: "Debugging Copilot Prompts",
    price: 20,
    format: "Prompt Pack",
    role: "Engineers",
    job: "Turn a stack trace and a hunch into a reproducible root cause.",
    proof: "Repro -> isolate -> fix workflow.",
    pain: "Debugging sessions that go in circles without a structured approach.",
    queries: [
      "debugging prompts stack trace",
      "root cause analysis prompts AI",
      "structured debugging workflow prompts",
    ],
    utterances: [
      "I've been going in circles on this stack trace for an hour",
      "Need a structured way to get from hunch to root cause",
    ],
    landing: "/product/AI-PP-042",
  },
  {
    sku: "AI-PP-043",
    name: "Exam Study Prompt Pack",
    price: 14,
    format: "Prompt Pack",
    role: "Students & Researchers",
    job: "Turn a dense syllabus into a study plan you can actually finish, using active recall and spaced repetition.",
    proof: "Works with Claude, ChatGPT, Gemini.",
    pain: "A syllabus so dense you don't know where to start studying.",
    queries: [
      "exam study prompts active recall",
      "spaced repetition study plan AI",
      "turn syllabus into study plan",
    ],
    utterances: [
      "This syllabus is so dense I don't know where to even start",
      "Need a study plan I can actually finish, not just start",
    ],
    landing: "/product/AI-PP-043",
  },
  {
    sku: "AI-TP-044",
    name: "Course Notes System",
    price: 12,
    format: "Template",
    role: "Students & Researchers",
    job: "Give every class a Cornell-style notes page with summaries, cue columns, and one-click review.",
    proof: "Duplicate-and-go, one page per course.",
    pain: "Notes scattered across apps with no consistent system.",
    queries: [
      "cornell notes notion template",
      "course notes system students",
      "one click review notes template",
    ],
    utterances: [
      "My notes are scattered across five different apps",
      "Want one notes system I actually use for every class",
    ],
    landing: "/product/AI-TP-044",
  },
  {
    sku: "AI-AG-045",
    name: "Essay Feedback Agent",
    price: 24,
    format: "Agent",
    role: "Students & Researchers",
    job: "Read your draft like a TA and return line-level feedback on argument, structure, and clarity — never writes it for you.",
    proof: "Rubric-scored, plagiarism-safe by design.",
    pain: "No TA available at 11pm the night before it's due.",
    queries: [
      "essay feedback AI agent",
      "line level essay feedback tool",
      "argument structure feedback writing",
    ],
    utterances: [
      "No TA available at 11pm the night before this is due",
      "Want real feedback on my argument, not just grammar fixes",
    ],
    landing: "/product/AI-AG-045",
  },
  {
    sku: "AI-PP-046",
    name: "Lecture-to-Flashcards Prompts",
    price: 13,
    format: "Prompt Pack",
    role: "Students & Researchers",
    job: "Turn a lecture transcript or your notes into clean question-and-answer cards ready to import.",
    proof: "Anki + Quizlet CSV export.",
    pain: "Making flashcards by hand after every lecture.",
    queries: [
      "lecture transcript to flashcards",
      "auto generate anki cards from notes",
      "notes to quizlet prompts",
    ],
    utterances: [
      "Making flashcards by hand after every single lecture is exhausting",
      "Want my lecture notes turned into cards automatically",
    ],
    landing: "/product/AI-PP-046",
  },
  {
    sku: "AI-TP-047",
    name: "Semester Planner Template",
    price: 15,
    format: "Template",
    role: "Students & Researchers",
    job: "Track every course, deadline, and grade in one place with a running GPA.",
    proof: "Assignment tracker + GPA calculator.",
    pain: "Deadlines tracked in your head until you miss one.",
    queries: [
      "semester planner template",
      "GPA tracker google sheets",
      "assignment deadline tracker students",
    ],
    utterances: [
      "I track deadlines in my head and it finally caught up with me",
      "Want one place for every course, deadline, and grade",
    ],
    landing: "/product/AI-TP-047",
  },
  {
    sku: "AI-AB-048",
    name: "Citation Formatter Automation",
    price: 19,
    format: "Automation",
    role: "Students & Researchers",
    job: "Drop in a link or DOI and get a correctly formatted reference added to your bibliography automatically.",
    proof: "APA, MLA & Chicago - Zotero sync.",
    pain: "Formatting citations by hand and still getting the style wrong.",
    queries: [
      "automatic citation formatter",
      "DOI to APA citation automation",
      "zotero citation sync tool",
    ],
    utterances: [
      "I still get the citation format wrong after formatting it by hand",
      "Want citations added automatically, not typed one at a time",
    ],
    landing: "/product/AI-AB-048",
  },
  {
    sku: "AI-AG-049",
    name: "Study Buddy Tutor Agent",
    price: 22,
    format: "Agent",
    role: "Students & Researchers",
    job: "Ask the next question instead of handing you the answer, so the concept actually sticks.",
    proof: "Presets for STEM, humanities & languages.",
    pain: "Tutors (and AI) that just give you the answer so nothing sticks.",
    queries: [
      "socratic tutor AI agent",
      "AI that asks questions instead of answers",
      "study buddy tutor STEM",
    ],
    utterances: [
      "Every AI tutor just gives me the answer and nothing sticks",
      "Want to be asked the next question, not handed the answer",
    ],
    landing: "/product/AI-AG-049",
  },
  {
    sku: "AI-AG-111",
    name: "Closed Chair",
    price: 36,
    format: "Agent",
    role: "Students & Researchers",
    job: "Answer only from your loaded syllabus — refuses to fetch the internet, invent a policy, or finish the problem for you.",
    proof: "Packet-only knowledge - refuses finished answers - syllabus-verb exam prep.",
    pain: "AI study tools that answer from the whole internet instead of your actual class.",
    queries: [
      "AI office hours syllabus only",
      "AI tutor that wont just give the answer",
      "class specific AI study tool",
    ],
    utterances: [
      "My AI tutor answers from the whole internet, not my actual syllabus",
      "Want office hours that only know what's actually in my class",
    ],
    landing: "/product/AI-AG-111",
  },
  {
    sku: "AI-TP-051",
    name: "Meeting Agenda & Minutes Template",
    price: 12,
    format: "Template",
    role: "Office & Admin",
    job: "Walk into a meeting with a tight agenda and walk out with decisions, owners, and dates written down.",
    proof: "Agenda + action-item tracker in one.",
    pain: "Meetings that end with no one sure what was decided.",
    queries: [
      "meeting agenda minutes template",
      "action item tracker meeting notion",
      "decisions owners dates template",
    ],
    utterances: [
      "That meeting ended and nobody's sure what was actually decided",
      "Need agendas that turn into action items automatically",
    ],
    landing: "/product/AI-TP-051",
  },
  {
    sku: "AI-AB-052",
    name: "Expense Report Automation",
    price: 23,
    format: "Automation",
    role: "Office & Admin",
    job: "Turn a folder of receipts into a categorized, submission-ready expense report without the manual typing.",
    proof: "Gmail + Drive + Sheets - OCR line items.",
    pain: "A folder of receipts and an afternoon lost to manual expense entry.",
    queries: [
      "automate expense report from receipts",
      "OCR receipts to expense report",
      "zapier expense report automation",
    ],
    utterances: [
      "Lost my afternoon typing receipts into an expense report again",
      "Need this folder of receipts turned into a report automatically",
    ],
    landing: "/product/AI-AB-052",
  },
  {
    sku: "AI-AG-053",
    name: "Calendar Scheduling Agent",
    price: 26,
    format: "Agent",
    role: "Office & Admin",
    job: "Handle the back-and-forth of finding a time, then book the meeting and send the invite.",
    proof: "Google + Outlook calendar aware.",
    pain: "Ten emails just to find a meeting time everyone can do.",
    queries: [
      "AI meeting scheduling agent",
      "automate calendar back and forth",
      "book meeting agent google outlook",
    ],
    utterances: [
      "Ten emails deep just trying to find a time that works",
      "Want scheduling handled without the back-and-forth",
    ],
    landing: "/product/AI-AG-053",
  },
  {
    sku: "AI-TP-054",
    name: "Standard Operating Procedure Kit",
    price: 17,
    format: "Template",
    role: "Office & Admin",
    job: "Capture how work actually gets done so a task survives vacations, handoffs, and new hires.",
    proof: "Step-by-step SOP + onboarding checklist.",
    pain: "The one person who knows how this works is on vacation.",
    queries: [
      "SOP template notion",
      "standard operating procedure kit",
      "onboarding checklist template business",
    ],
    utterances: [
      "The only person who knows how this works is on vacation",
      "Need this written down before it only lives in one person's head",
    ],
    landing: "/product/AI-TP-054",
  },
  {
    sku: "AI-AG-055",
    name: "Portfolio Rebalancing Analyst",
    price: 44,
    format: "Agent",
    role: "Finance & Investing",
    job: "Read your holdings and target allocation, then tell you exactly what to buy and sell to get back on track.",
    proof: "Drift bands + tax-lot aware.",
    pain: "A portfolio that's drifted from target with no clear plan to fix it.",
    queries: [
      "portfolio rebalancing tool",
      "tax lot aware rebalancing agent",
      "target allocation drift calculator",
    ],
    utterances: [
      "My portfolio has drifted way off target and I don't know what to sell",
      "Want exact buy/sell numbers, not just 'you should rebalance'",
    ],
    landing: "/product/AI-AG-055",
  },
  {
    sku: "AI-AG-056",
    name: "Earnings Call Copilot",
    price: 46,
    format: "Agent",
    role: "Finance & Investing",
    job: "Turn a raw earnings transcript into the thesis, the risks, and the three numbers that actually moved the stock.",
    proof: "Guidance + sentiment + KPI extraction.",
    pain: "A 90-minute earnings call and no time to find what actually mattered.",
    queries: [
      "earnings call transcript summarizer",
      "extract KPIs from earnings call",
      "earnings call thesis risk agent",
    ],
    utterances: [
      "Ninety minutes of earnings call and I still don't know what moved the stock",
      "Need the three numbers that mattered, not the whole transcript",
    ],
    landing: "/product/AI-AG-056",
  },
  {
    sku: "AI-AG-058",
    name: "DCF Valuation Agent",
    price: 49,
    format: "Agent",
    role: "Finance & Investing",
    job: "Feed it the fundamentals and get a discounted-cash-flow valuation with bull, base, and bear cases.",
    proof: "Sensitivity table + WACC presets.",
    pain: "Building a DCF from scratch every time instead of from a solid base case.",
    queries: [
      "DCF valuation agent AI",
      "discounted cash flow model generator",
      "bull base bear case valuation tool",
    ],
    utterances: [
      "Building this DCF from scratch again instead of starting from a real base case",
      "Want bull/base/bear cases, not just one number",
    ],
    landing: "/product/AI-AG-058",
  },
  {
    sku: "AI-AG-094",
    name: "$Token Agent",
    price: 44,
    format: "Agent",
    role: "Finance & Investing",
    job: "Read filings, headlines, and trend noise and return a sourced shortlist — never a trade.",
    proof: "Thesis + sources + kill-criteria - NO TRADE is a valid run.",
    pain: "Hours scrolling crypto Twitter for a thesis that's actually sourced.",
    queries: [
      "crypto research agent sourced thesis",
      "token research shortlist AI",
      "crypto trend analysis no hype",
    ],
    utterances: [
      "Scrolled crypto twitter for an hour and got zero actual sources",
      "Want a shortlist with real sources, not just vibes",
    ],
    landing: "/product/AI-AG-094",
  },
  {
    sku: "AI-AG-114",
    name: "$Odds Agent",
    price: 44,
    format: "Agent",
    role: "Finance & Investing",
    job: "Check a Polymarket link against live price and headlines, and flag a real divergence — never a trade.",
    proof: "NO FLAG is a valid run - never places a trade.",
    pain: "Thinking you have an edge on a prediction market without actually checking.",
    queries: [
      "polymarket divergence checker",
      "prediction market edge analysis tool",
      "check prediction market price vs news",
    ],
    utterances: [
      "Everyone thinks they have an edge on these markets and most don't",
      "Want to actually check the divergence, not just guess I have an edge",
    ],
    landing: "/product/AI-AG-114",
  },
  {
    sku: "AI-AB-059",
    name: "Receipt-to-Ledger Automation",
    price: 29,
    format: "Automation",
    role: "Finance & Investing",
    job: "Turn a photo or PDF of a receipt into a categorized, tax-ready ledger entry — no manual typing.",
    proof: "OCR + tax-category mapping.",
    pain: "A shoebox of receipts at tax time.",
    queries: [
      "receipt to ledger automation",
      "OCR receipt tax categorization",
      "automate bookkeeping from receipts",
    ],
    utterances: [
      "It's tax time and I have a literal shoebox of receipts",
      "Need receipts turned into ledger entries automatically, not typed",
    ],
    landing: "/product/AI-AB-059",
  },
  {
    sku: "AI-PP-061",
    name: "Financial Modeling Prompt Pack",
    price: 26,
    format: "Prompt Pack",
    role: "Finance & Investing",
    job: "Build three-statement models, unit economics, and scenario analyses without staring at a blank spreadsheet.",
    proof: "Excel + Google Sheets formulas.",
    pain: "A blank spreadsheet and a three-statement model due tomorrow.",
    queries: [
      "financial modeling prompts",
      "three statement model prompt pack",
      "unit economics prompts AI",
    ],
    utterances: [
      "Staring at a blank spreadsheet with this model due tomorrow",
      "Need a starting point for this three-statement model, not a blank tab",
    ],
    landing: "/product/AI-PP-061",
  },
  {
    sku: "AI-PP-062",
    name: "Equity Research Prompt Pack",
    price: 24,
    format: "Prompt Pack",
    role: "Finance & Investing",
    job: "Turn a 10-K into an investment thesis with catalysts, risks, and a price target.",
    proof: "10-K / 10-Q teardown workflow.",
    pain: "A 200-page 10-K and no structured way to turn it into a thesis.",
    queries: [
      "10-K teardown prompts",
      "equity research prompt pack",
      "investment thesis from 10-K AI",
    ],
    utterances: [
      "This 10-K is 200 pages and I need a thesis out of it by Friday",
      "Want a structured way to turn a filing into an actual thesis",
    ],
    landing: "/product/AI-PP-062",
  },
  {
    sku: "AI-TP-063",
    name: "Investor-Ready Financials Template",
    price: 22,
    format: "Template",
    role: "Finance & Investing",
    job: "Fill the revenue, burn, and runway model investors expect from your actual numbers, not a blank tab.",
    proof: "P&L + burn + runway + cap table.",
    pain: "Building investor financials from scratch the week of the raise.",
    queries: [
      "investor ready financial model template",
      "startup burn runway template",
      "cap table template sheets",
    ],
    utterances: [
      "Building our investor financials from scratch during the raise itself",
      "Need the model investors actually expect, not a generic template",
    ],
    landing: "/product/AI-TP-063",
  },
  {
    sku: "AI-TP-064",
    name: "Personal Budget & Net-Worth Template",
    price: 15,
    format: "Template",
    role: "Finance & Investing",
    job: "Track every account, bill, and goal in one place with a net-worth line that updates as you go.",
    proof: "50/30/20 + net-worth tracker.",
    pain: "Money spread across five apps with no single real number.",
    queries: [
      "personal budget net worth template",
      "50 30 20 budget sheet",
      "net worth tracker spreadsheet",
    ],
    utterances: [
      "My money is spread across five apps and I don't actually know my net worth",
      "Want one real number for net worth, not five different apps",
    ],
    landing: "/product/AI-TP-064",
  },
  {
    sku: "AI-CN-009",
    name: "MultiConnect: Google Docs",
    price: 39,
    format: "Connector",
    role: "Founders & Ops",
    job: "Export Google Docs to real local markdown files on a schedule, so local tools can actually see the content.",
    proof: "Read-only Drive access, revocable anytime, zero npm dependencies.",
    pain: "Local-file AI tools that can't see anything actually living in Google Docs.",
    queries: [
      "export google docs to markdown automatically",
      "google drive to local markdown sync",
      "google docs read only export tool",
    ],
    utterances: [
      "My local AI tools can't see anything that's actually in Google Docs",
      "Drive sync just gives me pointer files, not the real content",
    ],
    landing: "/product/AI-CN-009",
  },
];

export function productBySku(sku: string) {
  return PRODUCTS.find((p) => p.sku === sku);
}

export function productImageSrc(sku: string) {
  // Was `/products/${sku}.jpg` — a path that exists on neither this app's
  // own domain nor the main site. Real product photos are served by
  // multinicheai.com's Product-image.mts edge function at
  // /product-image/<sku>.png (see netlify/edge-functions/Product-image.mts
  // in the Jblessd repo), and SWARM is a separate Vercel deployment, so this
  // needs the absolute URL, not a same-origin relative path.
  return `${SITE}/product-image/${sku}.png`;
}

export function productsForRole(role: string) {
  return PRODUCTS.filter((p) => p.role === role);
}

export const ROLES = [...new Set(PRODUCTS.map((p) => p.role))];
export const FORMATS = [...new Set(PRODUCTS.map((p) => p.format))];

export function productUrl(product: Product, extra: Record<string, string> = {}) {
  const url = new URL(product.landing, SITE);
  url.searchParams.set("utm_source", "swarm");
  for (const [k, v] of Object.entries(extra)) url.searchParams.set(k, v);
  return url.toString();
}
