import type { Product } from "./types";

export const SITE = "https://multinicheai.com";
export const BRAND = "MULTINICHE AI";
export const COPYRIGHT_YEAR = 2026;
export const COPYRIGHT = `© ${COPYRIGHT_YEAR} ${BRAND}. All rights reserved.`;
export const SWARM_SKU = "AI-AB-070";
export const SWARM_REPO = "https://github.com/duprejesse3-ops/swarm";

export const PRODUCTS: Product[] = [
  {
    sku: "AI-AB-070",
    name: "SWARM Intent Autopilot",
    price: 79,
    format: "Automation",
    role: "Store & Site Owners",
    job: "Hijack demand that already exists and evolve proof-first ads on autopilot",
    proof: "Autopilot maps a pain-utterance to a SKU, spawns eight organisms, evolves winners — no click",
    pain: "A catalog of instruments and nobody intercepts the sentences people already type.",
    queries: [
      "automate ads for ai tools site",
      "intent hijack ads not google tax",
      "autopilot ads for digital products",
    ],
    utterances: [
      "I have a catalog and no traffic",
      "Buying Google ads for AI tools is a tax",
      "Need ads that intercept the job people already typed",
    ],
    landing: "/product/AI-AB-070",
  },
  {
    sku: "AI-AB-002",
    name: "Inbox Zero Automation",
    price: 29,
    format: "Automation",
    role: "Sales & CS",
    job: "Zero an inbox without losing the messages that need a human",
    proof: "2,400-email dump sorted, drafted, and flagged in 11 minutes",
    pain: "Inbox is a second job. ChatGPT drafts one reply. The pile is still there.",
    queries: [
      "inbox zero automation",
      "ai email sorter that drafts replies",
      "zapier gmail auto draft",
    ],
    utterances: [
      "I am drowning in Gmail and ChatGPT is not helping",
      "Need something that sorts AND drafts, not another summarizer",
      "Inbox zero without living in my email",
    ],
    landing: "/proof",
  },
  {
    sku: "AI-AG-003",
    name: "Meeting Notes Agent",
    price: 15,
    format: "Agent",
    role: "Founders & Ops",
    job: "Turn a transcript into decisions, owners, and deadlines",
    proof: "47-minute standup → 9 decisions, 6 owners, 4 dates — no summary fluff",
    pain: "Notes that recap what was said instead of what was decided.",
    queries: [
      "ai meeting notes with action items",
      "transcript to owners and deadlines",
      "meeting notes agent not summarizer",
    ],
    utterances: [
      "I need action items from meetings, not a recap",
      "Who owns what from yesterday's call",
      "Meeting notes that extract decisions",
    ],
    landing: "/agent",
  },
  {
    sku: "AI-PP-001",
    name: "Deep Work Prompt Pack",
    price: 19,
    format: "Prompt Pack",
    role: "Founders & Ops",
    job: "Protect focus blocks and close the day clean",
    proof: "Priority stack + 90-minute block + end-of-day reset in one pack",
    pain: "Todo lists that grow. No operating rhythm.",
    queries: [
      "deep work prompts chatgpt",
      "daily prioritization prompt pack",
      "end of day reset ai",
    ],
    utterances: [
      "I keep starting the day in other people's priorities",
      "Need a shutdown ritual that actually sticks",
      "Deep work system for a solo founder",
    ],
    landing: "/",
  },
  {
    sku: "AI-AB-005",
    name: "Content Calendar Autopilot",
    price: 24,
    format: "Automation",
    role: "Marketers",
    job: "Draft posts from notes and queue them by channel",
    proof: "One notes dump → 12 queued posts across 3 channels",
    pain: "A Notion calendar that is empty by Wednesday.",
    queries: [
      "ai content calendar automation",
      "draft social posts from notes",
      "queue linkedin twitter from one doc",
    ],
    utterances: [
      "I have notes but no posts go out",
      "Need a content engine that queues itself",
      "Tired of rewriting the same idea for every channel",
    ],
    landing: "/",
  },
  {
    sku: "AI-AG-020",
    name: "Autonomous SEO Content Agent",
    price: 46,
    format: "Agent",
    role: "Marketers",
    job: "Research, draft, and internally link an article on a topic you name",
    proof: "One topic in → sourced draft with internal links, not a spun blog",
    pain: "Paying for 10 generic AI posts that rank for nothing.",
    queries: [
      "ai seo writer with internal linking",
      "autonomous content agent",
      "keyword to article with sources",
    ],
    utterances: [
      "Need SEO content that is not obviously AI sludge",
      "Want an agent that researches then writes",
      "Internal linking is the part I always skip",
    ],
    landing: "/agent",
  },
  {
    sku: "AI-PP-025",
    name: "Viral Hook Prompt Pack",
    price: 23,
    format: "Prompt Pack",
    role: "Marketers",
    job: "Write openings that stop the scroll on each platform",
    proof: "Platform-tuned hooks — not one line pasted everywhere",
    pain: "Good posts dying on line one.",
    queries: [
      "viral hook prompts",
      "scroll stopping opening lines",
      "linkedin hook formula ai",
    ],
    utterances: [
      "My posts die in the first line",
      "Need hooks that match the platform rhythm",
      "Tired of 'are you struggling with' openers",
    ],
    landing: "/",
  },
  {
    sku: "AI-PP-014",
    name: "Landing Page Copy Prompts",
    price: 18,
    format: "Prompt Pack",
    role: "Marketers",
    job: "Headline, hero, and CTA variants for conversion tests",
    proof: "8 headline / hero / CTA sets ready to A/B, not one pretty draft",
    pain: "One hero line you are too close to judge.",
    queries: [
      "landing page copy prompts",
      "headline variants for ab test",
      "hero cta prompt pack",
    ],
    utterances: [
      "I need headline variants not another rewrite",
      "Landing page copy that is testable",
      "Hero section sounds like every other SaaS",
    ],
    landing: "/",
  },
  {
    sku: "AI-AG-008",
    name: "Daily Standup Bot",
    price: 18,
    format: "Agent",
    role: "Developers",
    job: "Collect async updates and post a one-line team digest",
    proof: "Async standups → one digest, no 15-minute meeting",
    pain: "Standup that exists so standup can exist.",
    queries: [
      "async standup bot",
      "slack daily digest agent",
      "replace standup with ai digest",
    ],
    utterances: [
      "Standup is eating the morning",
      "Need async updates that someone actually reads",
      "Replace the 15 minute meeting",
    ],
    landing: "/agent",
  },
  {
    sku: "AI-AB-013",
    name: "Code Review Digest",
    price: 26,
    format: "Automation",
    role: "Developers",
    job: "Summarize open PRs into a daily digest with risk flags",
    proof: "Open PRs → risk-flagged digest before you open GitHub",
    pain: "PR tab as a second inbox.",
    queries: [
      "pr digest automation",
      "daily code review summary",
      "flag risky pull requests",
    ],
    utterances: [
      "I have 14 open PRs and no idea which is dangerous",
      "Need a morning digest of code review",
      "GitHub notifications are unusable",
    ],
    landing: "/",
  },
  {
    sku: "AI-AG-016",
    name: "RAG Knowledge Base Agent",
    price: 44,
    format: "Agent",
    role: "Developers",
    job: "Turn docs into a grounded assistant that cites, not guesses",
    proof: "Answers with citations from your corpus — refuses when it cannot",
    pain: "A chatbot that hallucinates your own handbook.",
    queries: [
      "rag agent with citations",
      "docs assistant that does not hallucinate",
      "grounded knowledge base agent",
    ],
    utterances: [
      "Our internal bot makes up policies",
      "Need answers with citations from our docs",
      "RAG that refuses when it does not know",
    ],
    landing: "/agent",
  },
  {
    sku: "AI-PP-011",
    name: "Writing Style Prompt Kit",
    price: 16,
    format: "Prompt Pack",
    role: "Writers",
    job: "Lock tone so drafts sound like you",
    proof: "Voice lock you can hand to any model — ChatGPT, Claude, Gemini",
    pain: "Every draft sounds like a template.",
    queries: [
      "writing style prompt kit",
      "make chatgpt sound like me",
      "brand voice system prompt",
    ],
    utterances: [
      "ChatGPT does not sound like me",
      "Need a voice lock I can reuse",
      "Drafts come out corporate even when I am not",
    ],
    landing: "/",
  },
  {
    sku: "AI-PP-029",
    name: "Voice & Tone Cloner",
    price: 19,
    format: "Prompt Pack",
    role: "Writers",
    job: "Capture any brand voice into a reusable system prompt",
    proof: "Paste 3 samples → a system prompt you can hand to any model",
    pain: "Brand guidelines nobody's model follows.",
    queries: [
      "clone writing voice prompt",
      "brand tone system prompt",
      "voice cloner for chatgpt",
    ],
    utterances: [
      "I want to clone a newsletter voice",
      "Brand tone dies the moment we open ChatGPT",
      "Need a reusable voice prompt from samples",
    ],
    landing: "/",
  },
  {
    sku: "AI-PP-006",
    name: "Research Assistant Prompts",
    price: 22,
    format: "Prompt Pack",
    role: "Students & Researchers",
    job: "Literature scans and source comparison without mush",
    proof: "Structured scans that keep sources attached to claims",
    pain: "A 2,000-word 'overview' with no citations you can trust.",
    queries: [
      "literature review prompts",
      "ai research assistant with sources",
      "compare papers prompt pack",
    ],
    utterances: [
      "Need a literature scan that keeps the sources",
      "ChatGPT mashed three papers into mush",
      "Research prompts that compare instead of summarize",
    ],
    landing: "/",
  },
  {
    sku: "AI-AG-017",
    name: "Multi-Agent Research Swarm",
    price: 39,
    format: "Agent",
    role: "Students & Researchers",
    job: "Dispatch parallel researchers, merge into one sourced brief",
    proof: "Parallel agents, one sourced brief — not three conflicting essays",
    pain: "One model, one shallow pass.",
    queries: [
      "multi agent research",
      "parallel research agents brief",
      "ai literature swarm",
    ],
    utterances: [
      "One model is too shallow for this review",
      "Want agents to disagree then merge",
      "Need a sourced brief not three essays",
    ],
    landing: "/agent",
  },
  {
    sku: "AI-AB-018",
    name: "Support Triage Copilot",
    price: 42,
    format: "Automation",
    role: "Sales & CS",
    job: "Read inbound tickets, draft a reply, route the hard ones",
    proof: "Every ticket drafted; only the hard ones reach a human",
    pain: "First-response SLA dying in a shared inbox.",
    queries: [
      "support ticket triage ai",
      "draft reply and route tickets",
      "helpdesk copilot automation",
    ],
    utterances: [
      "We are missing first-response SLA",
      "Need triage that drafts, not just tags",
      "Shared inbox is eating the support team",
    ],
    landing: "/",
  },
  {
    sku: "AI-AB-010",
    name: "Personal CRM Automation",
    price: 25,
    format: "Automation",
    role: "Sales & CS",
    job: "Follow up before a relationship goes cold",
    proof: "Nudges you before the thread dies — not after",
    pain: "A CRM you never open, relationships you lose.",
    queries: [
      "personal crm follow up automation",
      "relationship reminder not salesforce",
      "follow up before they go cold",
    ],
    utterances: [
      "I lose people because I forget to follow up",
      "Need a lightweight CRM that nags me",
      "Relationships going cold in my inbox",
    ],
    landing: "/",
  },
  {
    sku: "AI-AG-015",
    name: "Realtime Voice Agent Blueprint",
    price: 49,
    format: "Agent",
    role: "Founders & Ops",
    job: "Answer calls, book meetings, hand off to a human",
    proof: "Production-ready voice agent — not a toy demo",
    pain: "Missed calls that should have been booked.",
    queries: [
      "realtime voice agent blueprint",
      "ai phone agent that books meetings",
      "production voice agent config",
    ],
    utterances: [
      "I miss calls that should have been meetings",
      "Need a voice agent that hands off, not a loop",
      "Want a production voice config not a demo",
    ],
    landing: "/agent",
  },
  {
    sku: "AI-TP-007",
    name: "Client Onboarding Kit",
    price: 34,
    format: "Template",
    role: "Sales & CS",
    job: "Intake, welcome sequence, and kickoff in one kit",
    proof: "Intake + welcome + kickoff — the first week stops being chaos",
    pain: "Every new client reinvented from Slack messages.",
    queries: [
      "client onboarding kit notion",
      "welcome sequence template",
      "kickoff checklist for agencies",
    ],
    utterances: [
      "Every new client is chaos for a week",
      "Need onboarding that is not a google doc graveyard",
      "Intake form plus kickoff in one kit",
    ],
    landing: "/",
  },
  {
    sku: "AI-AG-012",
    name: "Financial Categorizer Agent",
    price: 27,
    format: "Agent",
    role: "Founders & Ops",
    job: "Read bank exports and sort spend into your categories",
    proof: "CSV in → categories you defined, not a bank's guess",
    pain: "Sunday night with a CSV and a headache.",
    queries: [
      "categorize bank csv ai",
      "expense categorizer agent",
      "sort spend into my categories",
    ],
    utterances: [
      "Bank categories are useless",
      "Need my CSV sorted into MY buckets",
      "Expense review is eating Sunday",
    ],
    landing: "/agent",
  },
  {
    sku: "AI-AB-060",
    name: "Cashflow Forecast Automation",
    price: 33,
    format: "Automation",
    role: "Finance & Investing",
    job: "Project 13-week cashflow from invoices and bills",
    proof: "13-week cash view so the crunch is visible before it hits",
    pain: "Finding out you are short the week payroll lands.",
    queries: [
      "13 week cashflow forecast",
      "invoice bill cash projection",
      "see cash crunch before payroll",
    ],
    utterances: [
      "I find out we are short the week payroll hits",
      "Need a 13-week cash view",
      "Invoices and bills into one forecast",
    ],
    landing: "/",
  },
  {
    sku: "AI-AG-057",
    name: "Personal CFO Agent",
    price: 39,
    format: "Agent",
    role: "Finance & Investing",
    job: "Review spending, spot leaks, give three moves to hit the goal",
    proof: "Three moves toward the savings goal — not a lecture",
    pain: "Budget apps that shame you and do not tell you what to cut.",
    queries: [
      "personal cfo ai agent",
      "spending leaks three moves",
      "savings goal agent",
    ],
    utterances: [
      "I know I overspend I need the three cuts",
      "Budget apps lecture me",
      "Want a CFO not a pie chart",
    ],
    landing: "/agent",
  },
  {
    sku: "AI-AG-039",
    name: "On-Call Triage Agent",
    price: 45,
    format: "Agent",
    role: "Engineers",
    job: "Read the alert, pull the runbook, propose the first three checks",
    proof: "First three checks ready before you finish logging in",
    pain: "3am, twelve tabs, no first move.",
    queries: [
      "on call triage agent",
      "alert to runbook first checks",
      "pagerduty ai first three steps",
    ],
    utterances: [
      "3am and I do not know the first check",
      "Need the runbook pulled with the alert",
      "On-call is twelve tabs of archaeology",
    ],
    landing: "/agent",
  },
  {
    sku: "AI-AB-037",
    name: "Incident Postmortem Automation",
    price: 34,
    format: "Automation",
    role: "Engineers",
    job: "Turn an incident timeline into a blameless postmortem with owners",
    proof: "Timeline in → blameless draft with action items already assigned",
    pain: "Postmortems that never get written.",
    queries: [
      "incident postmortem automation",
      "blameless postmortem from timeline",
      "action items from incident",
    ],
    utterances: [
      "We never write the postmortem",
      "Need a blameless draft from the timeline",
      "Action items from incidents get lost",
    ],
    landing: "/",
  },
  {
    sku: "AI-AG-033",
    name: "Threat Modeling Agent",
    price: 41,
    format: "Agent",
    role: "Architects",
    job: "Walk a design and surface attack paths you missed",
    proof: "Attack paths, trust boundaries, mitigations — before you ship",
    pain: "Threat models that happen after the breach report.",
    queries: [
      "threat modeling agent",
      "attack paths from design doc",
      "ai stride threat model",
    ],
    utterances: [
      "We skip threat modeling until something breaks",
      "Need attack paths from a design doc",
      "Principal-level questions before the review",
    ],
    landing: "/agent",
  },
  {
    sku: "AI-AG-065",
    name: "Site Audit Agent",
    price: 79,
    format: "Agent",
    role: "Store & Site Owners",
    job: "A maintenance agent that watches your site on your hardware",
    proof: "Unzip, ./install.sh — site-audit command on your machine",
    pain: "Finding out the site is down from a customer.",
    queries: [
      "self hosted site audit agent",
      "website watchdog on my hardware",
      "install.sh site maintenance agent",
    ],
    utterances: [
      "I find out the site is down from a customer",
      "Want a watchdog that runs on my machine",
      "Need a site audit I actually own",
    ],
    landing: "/",
  },
  {
    sku: "AI-CN-004",
    name: "MultiConnect: Email/CRM",
    price: 79,
    format: "Connector",
    role: "Sales & CS",
    job: "Let an agent draft, send, and follow up — with approval control",
    proof: "Agent handles email with a human approval gate, not a runaway send",
    pain: "Agents that cannot touch email, or agents that send too much.",
    queries: [
      "ai agent email crm connector",
      "agent drafts with approval",
      "safe ai email follow up",
    ],
    utterances: [
      "I want an agent on email but I need an approval gate",
      "CRM follow-ups die because I will not give an agent send",
      "Need safe email automation",
    ],
    landing: "/",
  },
  {
    sku: "AI-CN-008",
    name: "MultiVault",
    price: 79,
    format: "Connector",
    role: "Founders & Ops",
    job: "Local encrypted snapshot of a folder — searchable, yours",
    proof: "Runs on your machine. No account. No cloud copy of the corpus.",
    pain: "Putting the company's files into someone else's chat box.",
    queries: [
      "local encrypted knowledge vault",
      "private ai over my folder",
      "no cloud document search",
    ],
    utterances: [
      "I will not upload the company folder to a chatbot",
      "Need local search over my files",
      "Private vault, no account",
    ],
    landing: "/",
  },
  {
    sku: "AI-HOST-001",
    name: "Meridian Host",
    price: 99,
    format: "Host",
    role: "Store & Site Owners",
    job: "Run the store on hardware you own",
    proof: "Perpetual license, no rent, site on your machine",
    pain: "A store that dies if a SaaS bill lapses.",
    queries: [
      "self host storefront",
      "run my shop on my hardware",
      "no subscription store host",
    ],
    utterances: [
      "I do not want my store on a rented platform",
      "Need to run the shop on my own hardware",
      "Tired of subscription hostages",
    ],
    landing: "/",
  },
  {
    sku: "AI-AG-030",
    name: "Customer Churn Sentinel",
    price: 43,
    format: "Agent",
    role: "Founders & Ops",
    job: "Flag at-risk accounts while there is still time",
    proof: "Usage + support signals → at-risk list before they cancel",
    pain: "Churn you notice in the cancellation email.",
    queries: [
      "churn prediction agent",
      "at risk accounts from usage",
      "save customers before they cancel",
    ],
    utterances: [
      "We notice churn in the cancellation email",
      "Need at-risk accounts while we can still save them",
      "Usage dropped and nobody saw it",
    ],
    landing: "/agent",
  },
  {
    sku: "AI-PP-050",
    name: "Professional Email Prompt Pack",
    price: 16,
    format: "Prompt Pack",
    role: "Office & Admin",
    job: "Say the hard thing well — declines, follow-ups, status",
    proof: "Warm, short, gets read — not a three-paragraph hedge",
    pain: "Staring at a blank reply for twenty minutes.",
    queries: [
      "professional email prompts",
      "how to decline politely prompt",
      "follow up email that gets read",
    ],
    utterances: [
      "I stare at hard emails for twenty minutes",
      "Need declines that stay warm",
      "Follow-ups that actually get a reply",
    ],
    landing: "/",
  },
];

export function productBySku(sku: string) {
  return PRODUCTS.find((p) => p.sku === sku);
}

export function productImageSrc(sku: string) {
  return `/products/${sku}.jpg`;
}

export function productsForRole(role: string) {
  return PRODUCTS.filter((p) => p.role === role);
}

export const ROLES = [...new Set(PRODUCTS.map((p) => p.role))];
export const FORMATS = [...new Set(PRODUCTS.map((p) => p.format))];

export function productUrl(product: Product, extra: Record<string, string> = {}) {
  const url = new URL(product.landing, SITE);
  url.searchParams.set("utm_source", "swarm");
  for (const [k, v] of Object.entries(extra)) url.searchParams.set(k, v);
  return url.toString();
}
