/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as EvolveRouteImport } from './routes/evolve'
import { Route as InstallRouteImport } from './routes/install'
import { Route as ProductRouteImport } from './routes/product'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SwarmRouteImport } from './routes/swarm'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolveRoute = EvolveRouteImport.update({
  id: '/evolve',
  path: '/evolve',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SwarmRoute = SwarmRouteImport.update({
  id: '/swarm',
  path: '/swarm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/evolve': typeof EvolveRoute
  '/install': typeof InstallRoute
  '/product': typeof ProductRoute
  '/studio': typeof StudioRoute
  '/swarm': typeof SwarmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/evolve': typeof EvolveRoute
  '/install': typeof InstallRoute
  '/product': typeof ProductRoute
  '/studio': typeof StudioRoute
  '/swarm': typeof SwarmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/evolve': typeof EvolveRoute
  '/install': typeof InstallRoute
  '/product': typeof ProductRoute
  '/studio': typeof StudioRoute
  '/swarm': typeof SwarmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/evolve'
    | '/install'
    | '/product'
    | '/studio'
    | '/swarm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/evolve'
    | '/install'
    | '/product'
    | '/studio'
    | '/swarm'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/evolve'
    | '/install'
    | '/product'
    | '/studio'
    | '/swarm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  EvolveRoute: typeof EvolveRoute
  InstallRoute: typeof InstallRoute
  ProductRoute: typeof ProductRoute
  StudioRoute: typeof StudioRoute
  SwarmRoute: typeof SwarmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolve': {
      id: '/evolve'
      path: '/evolve'
      fullPath: '/evolve'
      preLoaderRoute: typeof EvolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swarm': {
      id: '/swarm'
      path: '/swarm'
      fullPath: '/swarm'
      preLoaderRoute: typeof SwarmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  EvolveRoute: EvolveRoute,
  InstallRoute: InstallRoute,
  ProductRoute: ProductRoute,
  StudioRoute: StudioRoute,
  SwarmRoute: SwarmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
